name: Semgrep-SAST

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  semgrep-scan:
    name: Escaneo de Codigo
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Ejecutar Semgrep
        uses: semgrep/semgrep-action@v1
        with:
          config: p/default # Reglas estándar de seguridad para OWASP Top 10

