
name: Testiando la seguridad
on:
  pull_request:
    branches: [main, master]
jobs:
  analisis-de-seguridad:       # Corregido: Usamos guiones en vez de espacios en el nombre del Job
    runs-on: ubuntu-latest     # 4 espacios
    steps:                     # Corregido: Ahora tiene 4 espacios, alineado con 'runs-on'
      - name: Tarea1           # 6 espacios
        run: echo "Ejecutando el paso1"
      - name: Tarea2           # 6 espacios
        run: echo "ejectuando el paso2"

