name: Semgrep-SAST

on:
  pull_request:
    branches: [ "master" ] # Solo despierta con Pull Requests hacia master

jobs:
  semgrep-scan:
    name: Escaneo de Codigo
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Ejecutar Semgrep
        uses: semgrep/semgrep-action@v1
        with:
          config: p/javascript # Reglas estrictas de JavaScript
